query GroupSearch($query:String!, $limit: Float, $offset: Float) {
  groups: find_groups(searchString:$query, limit: $limit, offset:$offset){
    id
    name
    picture
    memberCount
    postCount
    privacy
    createdAt
    myMembership {
      id
      role
    }
  }
}
