fragment UserSummary on User {
  id
  firstname
  lastname
  badgeType
  username
  displayname
  profilePhotoURL
  bannerImageURL
  bio
  issuesOfInterestLocal
  issuesOfInterestNational
  location
}
