#import "../fragments/BasicPost.gql"

query ListBookmarkedPosts ($limit:Float, $offset:Float) {
  posts: list_bookmarked_posts (limit:$limit, offset:$offset){
  	... BasicPost
    group {
      id
      name
    }
    comments:replies(limit:1) {
      ... BasicPost
      comments:replies(limit:1) {
        ... BasicPost
      }
    }
    sharedPost {
      ... BasicPost
      comments:replies(limit:1) {
        ... BasicPost
        comments:replies(limit:1) {
          ... BasicPost
        }
      }
    }
  }
}
