mutation SetLeaders(
  $meetingId: String!
  $presenters: String
  $moderators: String
  $admins: String
) {
  set_leaders(
    meetingId: $meetingId
    presenters: $presenters
    moderators: $moderators
    admins: $admins
  )
}
